---
title: "likelihood"
author: "Briantama Asmara"
date: "10/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(here)
here()
```

# Load the data

```{r}
dat_bird = data.frame(read.csv(here("data", "bird.sta.csv")))
dat_habitat = data.frame(read.csv(here("data", "hab.sta.csv")))
dat_all = merge(dat_bird, dat_habitat)
```

```{r}
summary(dat_all$WIWA)
```

```{r}
hist(dat_all$WIWA)
```

```{r}
hist(dat_all$WIWA, breaks = 7)
```

```{r}
hist(dat_all$WIWA, breaks = 0:7)
```

```{r}
0:7 - 0.5
```


```{r}
hist(dat_all$WIWA, breaks = 0:7 - .5)
```

```{r}
par(mfrow = c(1, 2))
dat = dat_all$WIWA
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nWilson's Warbler counts")

dat = dat_all$GRJA
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nGray Jay counts")
```


```{r}
sum(log(dpois(x = dat_all$WIWA, lambda = 1.0)))
```

```{r}
wiwa_counts = c(2, 6)
dpois(x = wiwa_counts, lambda = 4.5)

```

```{r}
sum(log(dpois(x = dat_all$WIWA, lambda = 2.0)))
sum(log(dpois(x = dat_all$WIWA, lambda = 3.0)))
sum(log(dpois(x = dat_all$WIWA, lambda = 4.0)))
```
```{r}
summary(dat_all$WIWR)
```

n =  20

20 * probability = 1.45 (mean)

prob_guess = 1.45 / 20
```{r}
hist(dpois(x = dat_all$WIWR, lambda = 1.0))
```

```{r}
hist(dat_all$WIWR, 
     breaks = 0:(max(dat_all$WIWR) + 1) - 0.5, 
     main = "Histogram of\nWinter's Wren counts",
     xlab = "Counts of Winter's Wren")
```

```{r}
sum(log(dpois(x = dat_all$WIWR, lambda = 1.0)))
sum(log(dpois(x = dat_all$WIWR, lambda = 4.0)))
```

```{r}
summary(dat_all$WIWR)
```


```{r}
sum(log(dbinom(x = dat_all$WIWR, 6, 1/6)))
```
```{r}
dat_all$WIWR
```

