---
title: "t_test"
author: "Briantama Asmara"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(palmerpenguins)
```

```{r}
dat_ade = droplevels(subset(penguins, species == "Adelie"))

dat_ade_male = droplevels(subset(dat_ade, sex == "male"))

dat_ade_female = droplevels(subset(dat_ade, sex == "female"))
```

```{r}
dat_ade_male
```


```{r}
hist(dat_ade$body_mass_g, main = "Adelie Penguins: Body Mass", xlab = "body mass (g)")
```

```{r}
head(dat_ade)
```


```{r}
boxplot(body_mass_g ~ sex,
        data = dat_ade,
        main = "Body Mass of Adelie Penguin",
        xlab = "Sex",
        ylab = "Body Mass (g)")
```

```{r}
t.test(dat_ade$body_mass_g, mu=0)
```


```{r}
t.test(dat_ade_male$body_mass_g, mu=4000, alternative = "greater")
```

```{r}
t.test(dat_ade$body_mass_g ~ dat_ade$sex)
```

```{r}
t.test(dat_ade_male$body_mass_g, dat_ade_female$body_mass_g, alternative="greater")
```

```{r}
t.test(dat_ade_male$body_mass_g, dat_ade_female$body_mass_g, alternative="less")
```

