---
title: "Homepage of Briantama Asmara"

output:
    html_document:
      theme: paper
      toc: true
      toc_depth: 3
      toc_float: true

---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

Hello world!

This is the personal pages of Briantama Asmara. Love mapping, napping, and hiking. Sometimes watch Netflix.

Currently pursuing Master's degree in Environmental Conservation at University Massacusetts. With 2+ years of experience in the GIS field, Brian keeps pushing through the mapping industry by learning the cutting-edge of spatial technology. Its technical prowess in GIS software (ArcGIS, QGIS) combined with a programming language (Python, Django, PostGIS) has been the core skills for various projects, such as cleaning government databases. Currently, Brian is trying to master the cartography skills by combining GIS with design software (Photoshop, Illustrator, Blender). His aspiration to achieve the level of visualization from renowned cartographers, NatGeoMaps, NY Times, and Washington Post has tremendously inspired him to become one of the best in the field.

Probably in the future will be migrating to Github from my personal website at [mapsmerizing.com](mapsmerizing.com)

# Analysis of Environmental Data Assignments

## Final Assignments are finally here!

### 1. [Final Project Part 1: R Reference Guide](https://brayents.github.io/env_data/final_R_reference)
### 2. [Final Project Part 2: Data Analysis](https://brayents.github.io/env_data/final_part2)



# Projects

Check for [Personal Storytelling from 2019](https://brayents.github.io/sostory/)

# Portfolio

Check for Cartography portfolio [mapsmerizing.com](mapsmerizing.com)


# Resume
Resume is upcoming

